/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/contentScripts/ActionBar.vue')['default']
    ArcEditor: typeof import('./components/root/ArcEditor.vue')['default']
    ArcsEditor: typeof import('./components/root/ArcsEditor.vue')['default']
    Editor: typeof import('./components/block/editor.vue')['default']
    Explain: typeof import('./components/sidepanel/Explain.vue')['default']
    Loading: typeof import('./components/common/loading.vue')['default']
    Logo: typeof import('./components/common/logo.vue')['default']
    Suggestion: typeof import('./components/contentScripts/Suggestion.vue')['default']
    TakingNote: typeof import('./components/sidepanel/TakingNote.vue')['default']
    WritingAssist: typeof import('./components/contentScripts/WritingAssist.vue')['default']
  }
}
